In [3]:
import numpy as np
import scipy as sp
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
from statsmodels.formula.api import ols

pd.options.mode.chained_assignment = None

In [7]:
prediction = pd.read_csv('../data/raw/Prediction of rental price based on suburbs.csv')
Top10 = pd.read_csv('../data/raw/rank of suburbs and growth rate.csv')

In [8]:
prediction

,Unnamed: 0,Suburb,Rental_price_now,Prediction_2023,Prediction_2024,Prediction_2025,avg_growth_rate
0,0,Korumburra,278.333333,282.269943,286.309350,290.454241,0.014310
1,1,Kew,621.281250,627.072254,633.010621,639.100101,0.009470
2,2,Glen Waverley,561.269841,563.489776,565.745730,568.038307,0.004004
3,3,Sailors Falls,450.000000,454.675727,459.499186,464.475044,0.010609
4,4,Sunbury,471.617647,477.490167,483.534843,489.756724,0.012660
...,...,...,...,...,...,...,...
719,719,Montmorency,525.555556,532.379136,539.422071,546.691412,0.013230
720,720,Carrum Downs,458.823529,464.762870,470.886956,477.201535,0.013177
721,721,Mambourin,407.352941,412.161317,417.090713,422.144174,0.011960
722,722,Murtoa,300.000000,305.159093,310.483834,315.979544,0.017449
723,723,Chelsea,493.333333,501.278041,509.517137,518.061528,0.016437