In [37]:
import pandas as pd

In [38]:
population = pd.read_csv("../data/raw/population.csv")
population.head()

,Unnamed: 0,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,ERP 2020,ERP 2021,ERP Change Amount,ERP Change Rate,Natureal increase,Internal migration,Overseas migration,Area km2,density 2021 persons/km2
0,0,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,15030,16263,1233,8.2,117,1143,-27,52.7,308.5
1,1,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,12097,11931,-166,-1.4,-43,-107,-16,12.4,963.8
2,2,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011003,Ballarat - North,24606,24720,114,0.5,8,123,-17,92.4,267.7
3,3,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011004,Ballarat - South,25639,25543,-96,-0.4,83,-150,-29,32.9,777.5
4,4,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,7721,7668,-53,-0.7,33,-78,-8,51.6,148.6

In [39]:
properties= pd.read_csv("../data/raw/properties_preporcessed_1.csv")
properties.head()

,Unnamed: 0,name,cost_text,rooms,type,cloest station,station_distance,cloest school,school_distance,CBD_distance,...,text,beds,bath,parking,Longitude,Latitude,SA2_CODE21,LOC_PID,LOC_NAME,SA2_MAIN16
0,0,1901/368 St Kilda Road Melbourne VIC 3000,$1800 Per Week,"['3 Beds', '2 Baths', '2 Parking']",Apartment / Unit / Flat,30,1803.65,1374,667.06,1702.19,...,Per Week,3,2,2,144.971027,-37.831809,206051512.0,loc9901d119afda,Melbourne,206051132.0
1,1,1211/200 Spencer Street Melbourne VIC 3000,$480 per week,"['1 Bed', '1 Bath', '1 Parking']",Apartment / Unit / Flat,176,371.68,2265,352.49,2267.13,...,per week,1,1,1,144.953247,-37.816228,206041505.0,loc9901d119afda,Melbourne,206041122.0
2,2,1008/380 Little Lonsdale Street Melbourne VIC ...,$400 pw,"['1 Bed', '1 Bath']",Apartment / Unit / Flat,28,248.50,2189,401.73,1937.39,...,pw,1,1,0,144.958129,-37.812103,206041505.0,loc9901d119afda,Melbourne,206041122.0
3,3,3/27 Flinders Lane Melbourne VIC 3000,$420 per week,"['1 Bed', '1 Bath']",Apartment / Unit / Flat,140,404.26,2193,586.61,790.13,...,per week,1,1,0,144.973365,-37.814732,206041503.0,loc9901d119afda,Melbourne,206041122.0
4,4,611/408 Lonsdale Street Melbourne VIC 3000,$350,"['1 Bed', '1 Bath']",Apartment / Unit / Flat,28,525.08,2265,779.91,1657.95,...,NaN,1,1,0,144.960401,-37.812598,206041504.0,loc9901d119afda,Melbourne,206041122.0

In [40]:
df1 = population[['SA2 code','ERP 2021']]
df1.head()

    SA2 code  ERP 2021
0  201011001     16263
1  201011002     11931
2  201011003     24720
3  201011004     25543
4  201011005      7668

In [41]:
df1.shape

(462, 2)

In [42]:
df1['SA2 code'].value_counts().sort_values(ascending=False)

201011001    1
202021028    1
201011004    1
201011005    1
201011006    1
            ..
217031476    1
217041477    1
217041478    1
217041479    1
217041480    1
Name: SA2 code, Length: 462, dtype: int64

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SA2 code  462 non-null    int64
 1   ERP 2021  462 non-null    int64
dtypes: int64(2)
memory usage: 7.3 KB

In [44]:
df2 = properties[['LOC_NAME','SA2_MAIN16']]
df2 = df2.fillna(0)
df2['SA2_MAIN16']=df2['SA2_MAIN16'].astype(int)
df2.head()

    LOC_NAME  SA2_MAIN16
0  Melbourne   206051132
1  Melbourne   206041122
2  Melbourne   206041122
3  Melbourne   206041122
4  Melbourne   206041122

In [45]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14726 entries, 0 to 14725
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOC_NAME    14726 non-null  object
 1   SA2_MAIN16  14726 non-null  int64
dtypes: int64(1), object(1)
memory usage: 230.2+ KB

In [46]:
result={}

In [47]:
# Find the LOC_NAME for each SA2
for sa in df1['SA2 code']:
    result[sa]={}
    a = list(set(df2.loc[df2['SA2_MAIN16']==sa,:]['LOC_NAME']))
    a_df = df2.loc[df2['SA2_MAIN16']==sa,:]
    # The first type: one SA2 corresponds to multiple loc_NAME
    if len(a)>1:
        counts = 0
        counts_nums= []
        for locname in a:
            # The total number that each loc_name contains properties
            nums = a_df.loc[a_df['LOC_NAME']==locname,:].shape[0]
            # Calculate the weight for each loc_name
            counts+=nums
            counts_nums.append(nums)
        ratio = list(map(lambda x:x/counts, counts_nums))
        # According to the population value of each SA2 multiplied by the weight of locality, the population of different locality is calculated.
        for l in range(len(a)):
            result[sa][a[l]] = ratio[l]*population.loc[population['SA2 code']==sa,:]['ERP 2021'].values[0]
            
    # The second type: A SA2 corresponds to a loc_name
    elif len(a)==1:
        # Just give the value of the population in sa2 directly to that locality
        value = population.loc[population['SA2 code']==sa,:]['ERP 2021'].values[0]
        result[sa][a[0]]=value

In [48]:
result1 = {}
locality = list(set(df2['LOC_NAME']))
for loc in locality:
    # The third type: Multiple SA2 correspond to one locality.
    b = df2.loc[df2['LOC_NAME']==loc,:]
    b = b.drop_duplicates()
    if b.shape[0]>1:
        result1[loc]={}
        # The population of this loc_name is equal to the sum of the populations of SA2 belonging to this locality
        code = list(b['SA2_MAIN16'])
        v = 0
        for c in code:
            value = population.loc[population['SA2 code']==c,:]['ERP 2021'].values[0]
            v+=value
        result1[loc]=v

In [49]:
result

{201011001: {'Lucas': 5004.0, 'Cardigan': 417.0, 'Alfredton': 10842.0},
 201011002: {'Lake Wendouree': 2609.90625,
  'Bakery Hill': 745.6875,
  'Ballarat Central': 5592.65625,
  'Newington': 1491.375,
  'Lake Gardens': 1491.375},
 201011003: {'Eureka': 950.7692307692308,
  'Invermay Park': 475.3846153846154,
  'Ballarat East': 5704.615384615385,
  'Ballarat North': 2852.3076923076924,
  'Soldiers Hill': 4278.461538461538,
  'Black Hill': 4753.846153846154,
  'Brown Hill': 5229.2307692307695,
  'Nerrina': 475.3846153846154},
 201011004: {'Sebastopol': 7298.0,
  'Canadian': 7298.0,
  'Mount Pleasant': 3192.875,
  'Golden Point': 2280.625,
  'Redan': 3649.0,
  'Mount Clear': 1824.5},
 201011005: {'Buninyong': 2556.0, 'Mount Helen': 5112.0},
 201011006: {'Winter Valley': 6140.659090909091,
  'Smythes Creek': 909.7272727272727,
  'Delacombe': 1364.590909090909,
  'Bonshaw': 1592.0227272727273},
 201011007: {},
 201011008: {'Miners Rest': 1383.2727272727273,
  'Mount Rowan': 691.6363636363636,
  'Wendouree': 13141.09090909091},
 201021009: {'Korobeit': 2112.6666666666665, 'Ballan': 4225.333333333333},
 201021010: {'Creswick': 7165.375, 'Learmonth': 1023.625},
 201021011: {'Daylesford': 5287.777777777778,
  'Sailors Falls': 1057.5555555555554,
  'Hepburn Springs': 1057.5555555555554,
  'Trentham': 2115.111111111111},
 201021012: {'Gordon': 2038.0, 'Scotsburn': 2038.0, 'Bungaree': 2038.0},
 201031013: {},
 201031014: {'Beaufort': 4637},
 201031015: {'Scarsdale': 5008},
 201031016: {'Maryborough': 7977},
 201031017: {},
 202011018: {'Ironbark': 536.5925925925926,
  'Long Gully': 1609.7777777777776,
  'North Bendigo': 4113.876543209876,
  'Bendigo': 8227.753086419752},
 202011019: {'Jackass Flat': 2889.214285714286,
  'Eaglehawk': 5778.428571428572,
  'California Gully': 3852.285714285714,
  'Sailors Gully': 963.0714285714286},
 202011020: {'Kennington': 7509.885714285714,
  'Strathdale': 2766.8,
  'East Bendigo': 3557.3142857142852},
 202011021: {'Flora Hill': 5569.714285714285,
  'Spring Gully': 348.10714285714283,
  'Quarry Hill': 3829.1785714285716},
 202011022: {'Golden Square': 9063.91304347826,
  'Kangaroo Flat': 11783.086956521738},
 202011023: {'Maiden Gully': 5667},
 202011024: {'Strathfieldsaye': 9177.42857142857,
  'Junortoun': 1529.5714285714284},
 202011025: {'Huntly': 6728.181818181818,
  'White Hills': 4036.9090909090905,
  'Ascot': 1345.6363636363637,
  'Epsom': 2691.2727272727275},
 202021026: {},
 202021027: {'Castlemaine': 9492.5, 'McKenzie Hill': 1898.5},
 202021028: {'Guildford': 3020.0, 'Maldon': 6040.0},
 202021029: {'Knowsley': 1630.3333333333333, 'Heathcote': 3260.6666666666665},
 202021030: {'Kyneton': 10494},
 202021031: {'Woodend': 7789},
 202031032: {'Longlea': 4697},
 202031033: {'Inglewood': 1171.0,
  'Newbridge': 1171.0,
  'Boort': 3513.0,
  'Pyramid Hill': 1171.0},
 203011034: {'Bannockburn': 7725},
 203011035: {'Barunah Park': 3932.5, 'Steiglitz': 3932.5},
 203011036: {'Mount Moriac': 1565.5, 'Winchelsea': 4696.5},
 203021037: {'Belmont': 14678},
 203021038: {'Norlane': 10645.833333333334,
  'North Shore': 1520.8333333333333,
  'Corio': 13687.5,
  'Lovely Banks': 1520.8333333333333},
 203021039: {'Geelong': 8478.76923076923,
  'Breakwater': 794.8846153846155,
  'South Geelong': 1854.730769230769,
  'East Geelong': 1854.730769230769,
  'Thomson': 794.8846153846155},
 203021040: {'Fyansford': 319.3731343283582,
  'Manifold Heights': 1596.8656716417909,
  'Geelong West': 10858.686567164179,
  'Hamlyn Heights': 5109.9701492537315,
  'Herne Hill': 3513.10447761194},
 203021041: {'Waurn Ponds': 5190.461538461539,
  'Marshall': 1482.9890109890111,
  'Mount Duneed': 7785.6923076923085,
  'Charlemont': 4078.21978021978,
  'Grovedale': 8156.43956043956,
  'Armstrong Creek': 7044.197802197802},
 203021042: {'Highton': 24126},
 203021043: {'Lara': 19562.864864864867,
  'Little River': 575.3783783783784,
  'Anakie': 1150.7567567567569},
 203021044: {'Leopold': 13942},
 203021045: {'Whittington': 2987.6000000000004,
  'St Albans Park': 2987.6000000000004,
  'Moolap': 1493.8000000000002,
  'Newcomb': 7469.0},
 203021046: {'Newtown': 10905},
 203021047: {'Bell Park': 6234.400000000001,
  'Rippleside': 2493.76,
  'North Geelong': 3117.2000000000003,
  'Bell Post Hill': 2493.76,
  'Drumcondra': 1246.88},
 203031048: {'Clifton Springs': 6169.5, 'Curlewis': 9597.0, 'Drysdale': 685.5},
 203031049: {'Anglesea': 5851},
 203031050: {'Armstrong Creek': 13564.714285714284,
  'Connewarre': 437.57142857142856,
  'Ocean Grove': 10501.714285714286,
  'Barwon Heads': 6126.0},
 203031051: {'Portarlington': 4625.116279069767,
  'Indented Head': 1051.1627906976744,
  'St Leonards': 3363.720930232558},
 203031052: {'Point Lonsdale': 4279.714285714285,
  'Queenscliff': 713.2857142857142},
 203031053: {'Jan Juc': 918.3076923076924,
  'Bellbrae': 918.3076923076924,
  'Torquay': 22039.384615384617},
 204011054: {'Eildon': 1680.0,
  'Marysville': 1680.0,
  'Buxton': 1680.0,
  'Alexandra': 1680.0},
 204011055: {},
 204011056: {'Broadford': 5645.5, 'Kilmore': 10484.5},
 204011057: {'Merrijig': 2227.111111111111,
  'Mansfield': 4454.222222222222,
  'Goughs Bay': 2227.111111111111,
  'Maindample': 1113.5555555555554},
 204011058: {},
 204011059: {'Seymour': 6428},
 204011060: {'Hilldene': 4391},
 204011061: {},
 204011062: {'Flowerdale': 1956.0, 'Yea': 1956.0},
 204021063: {'Benalla': 10487},
 204021064: {'Thoona': 2790.0, 'Baddaginnie': 930.0},
 204021065: {'Rutherglen': 4091},
 204021066: {'Wangaratta': 19558},
 204021067: {'Bowmans Forest': 9821},
 204031068: {'Beechworth': 4929},
 204031069: {'Tawonga South': 5836.666666666666,
  'Wandiligong': 2918.333333333333},
 204031070: {},
 204031071: {'Merriang': 319.6, 'Myrtleford': 4474.4},
 204031072: {'Tallangatta East': 1511.25,
  'Dartmouth': 1511.25,
  'Corryong': 3022.5},
 204031073: {'West Wodonga': 15617},
 204031074: {'Bandiana': 861.53125,
  'Wodonga': 23261.34375,
  'Leneva': 861.53125,
  'Baranduda': 2584.59375},
 204031075: {'Tangambalanga': 4826},
 205011076: {'Longwarry': 2052.7241379310344,
  'Labertouche': 684.2413793103448,
  'Drouin': 17106.03448275862},
 205011077: {},
 205011078: {'Trafalgar': 8279},
 205011079: {'Warragul': 22272},
 205021080: {},
 205021081: {'Eastwood': 3141.0,
  'Bairnsdale': 9423.0,
  'Lucknow': 1047.0,
  'Wy Yung': 1047.0,
  'East Bairnsdale': 1047.0},
 205021082: {'Clifton Creek': 2111.5,
  'Lindenow': 2111.5,
  'Nicholson': 2111.5,
  'Ellaswood': 2111.5},
 205021083: {},
 205021084: {'Metung': 1793.3333333333333,
  'Kalimna West': 1195.5555555555554,
  'Swan Reach': 1195.5555555555554,
  'Lakes Entrance': 4782.222222222222,
  'Kalimna': 1793.3333333333333},
 205021085: {'Marlo': 3251.0, 'Cape Conran': 3251.0},
 205021086: {'Paynesville': 7076},
 205031087: {'Meeniyan': 1331.0,
  'Dumbalk': 1996.5,
  'Fish Creek': 665.5,
  'Venus Bay': 1331.0,
  'Foster': 3327.5,
  'Tarwin Lower': 665.5},
 205031088: {},
 205031089: {'Korumburra': 4897.0,
  'Bena': 1632.3333333333333,
  'Nyora': 3264.6666666666665},
 205031090: {'Mirboo North': 4618.400000000001,
  'Leongatha': 6927.599999999999},
 205031091: {'Cape Woolamai': 1046.0833333333333,
  'Sunset Strip': 1569.125,
  'Cowes': 7322.583333333334,
  'Ventnor': 523.0416666666666,
  'Wimbledon Heights': 523.0416666666666,
  'Smiths Beach': 523.0416666666666,
  'Sunderland Bay': 1046.0833333333333},
 205031092: {},
 205031093: {'Dalyston': 1335.5897435897436,
  'Cape Paterson': 667.7948717948718,
  'Wonthaggi': 8013.538461538462,
  'Grantville': 667.7948717948718,
  'Inverloch': 5342.358974358975,
  'Corinella': 1335.5897435897436,
  'San Remo': 1335.5897435897436,
  'North Wonthaggi': 3338.974358974359,
  'Pioneer Bay': 2003.3846153846155,
  'Coronet Bay': 2003.3846153846155},
 205041094: {'Churchill': 6540.0,
  'Koornalla': 1308.0,
  'Yinnar': 1308.0,
  'Callignee': 1308.0,
  'Hazelwood North': 1308.0},
 205041095: {'Newborough': 2296.5, 'Moe': 14544.5},
 205041096: {'Morwell': 14046},
 205041097: {'Traralgon': 28521},
 205041098: {'Glengarry North': 4817},
 205051099: {},
 205051100: {'Golden Beach': 1549.0, 'Seaspray': 3098.0},
 205051101: {'Stratford': 4862.333333333333,
  'Heyfield': 4862.333333333333,
  'Maffra': 4862.333333333333},
 205051102: {'Rosedale': 4852},
 205051103: {'Sale': 15388},
 205051104: {'Yarram': 1837.3333333333333,
  'Jack River': 1837.3333333333333,
  'Port Albert': 1837.3333333333333},
 206011105: {'Brunswick West': 444.469696969697,
  'Brunswick': 28446.060606060608,
  'Brunswick East': 444.469696969697},
 206011106: {'Brunswick East': 14164.59090909091,
  'Fitzroy North': 329.40909090909093},
 206011107: {'Brunswick West': 15596},
 206011108: {'Pascoe Vale South': 312.03225806451616,
  'Coburg': 28706.967741935485},
 206011109: {'Pascoe Vale South': 10109.866666666667,
  'Coburg': 722.1333333333333},
 206021110: {'Fairfield': 7602.608695652174, 'Alphington': 2389.391304347826},
 206021111: {'Thornbury': 502.7889908256881, 'Northcote': 26899.211009174312},
 206021112: {'Thornbury': 20281},
 206031113: {'Ascot Vale': 16530},
 206031114: {'Essendon': 25575.398058252427,
  'Aberfeldie': 1784.3300970873786,
  'Essendon North': 3271.271844660194},
 206031115: {'Travancore': 2535.661016949153, 'Flemington': 8150.338983050847},
 206031116: {'Moonee Ponds': 16195},
 206041117: {'Carlton': 22510.727272727272, 'Melbourne': 559.2727272727273},
 206041118: {'Docklands': 14821},
 206041119: {'East Melbourne': 5803},
 206041120: {'Flemington': 91},
 206041121: {'Kensington': 11836},
 206041122: {'Melbourne': 47192},
 206041123: {'North Melbourne': 15687.065573770491,
  'Melbourne': 143.91803278688525,
  'West Melbourne': 10506.016393442624},
 206041124: {'Parkville': 7964},
 206041125: {'South Yarra': 4141.4400000000005, 'Melbourne': 2329.56},
 206041126: {'Melbourne': 237.42342342342343, 'Southbank': 26116.576576576575},
 206041127: {},
 206051128: {'Albert Park': 4057.6470588235293,
  'Middle Park': 2231.7058823529414,
  'Melbourne': 10955.647058823528},
 206051129: {'Elwood': 15986},
 206051130: {'Port Melbourne': 17632},
 206051131: {'Port Melbourne': 800},
 206051132: {'Melbourne': 808.6585365853658,
  'South Melbourne': 12129.878048780489,
  'Southbank': 323.4634146341464},
 206051133: {'St Kilda': 24191.10280373832,
  'Melbourne': 2186.7663551401865,
  'Elwood': 136.67289719626166,
  'St Kilda West': 2323.4392523364486,
  'Windsor': 410.01869158878503},
 206051134: {'St Kilda': 798.7053571428571,
  'Balaclava': 6709.125,
  'Ripponlea': 479.2232142857143,
  'St Kilda East': 9903.94642857143},
 206061135: {'Armadale': 10213},
 206061136: {'Melbourne': 124.36627906976744,
  'Windsor': 6964.511627906977,
  'Armadale': 124.36627906976744,
  'Prahran': 14177.755813953487},
 206061137: {'South Yarra': 24171},
 206061138: {'Toorak': 13961},
 206071139: {'Abbotsford': 10103},
 206071140: {'Carlton North': 7386.693877551021,
  'Princes Hill': 1441.3061224489795},
 206071141: {'Collingwood': 11305},
 206071142: {'Fitzroy': 11399},
 206071143: {'Fitzroy North': 13505},
 206071144: {'Burnley': 975.1813953488372,
  'Richmond': 32180.98604651163,
  'Cremorne': 1787.832558139535},
 206071145: {'Fairfield': 367.5357142857143,
  'Clifton Hill': 6615.642857142858,
  'Alphington': 3307.821428571429},
 207011146: {'Ashburton': 8020},
 207011147: {'Mont Albert': 407.975, 'Deepdene': 2855.825, 'Balwyn': 13055.2},
 207011148: {'Balwyn North': 21245},
 207011149: {'Surrey Hills': 588.2933333333334,
  'Camberwell': 21472.70666666667},
 207011150: {'Camberwell': 2018.6046511627906, 'Glen Iris': 15341.39534883721},
 207011151: {'Hawthorn': 25058},
 207011152: {'Hawthorn East': 15138.103448275862,
  'Camberwell': 576.6896551724138,
  'Hawthorn': 1009.2068965517242},
 207011153: {'Kew': 26158},
 207011154: {'Kew East': 6884},
 207011155: {'Surrey Hills': 8388.0,
  'Camberwell': 335.52,
  'Canterbury': 8052.48},
 207021156: {'Doncaster': 451.03846153846155,
  'Bulleen': 10824.923076923078,
  'Templestowe Lower': 451.03846153846155},
 207021157: {'Doncaster': 25520},
 207021159: {'Templestowe': 17273},
 207021160: {'Doncaster': 754.0, 'Templestowe Lower': 13572.0},
 207021424: {'Doncaster East': 15478},
 207021425: {'Doncaster East': 15683},
 207031161: {'Blackburn North': 6359.1, 'Blackburn': 16764.899999999998},
 207031162: {'Blackburn South': 11165},
 207031163: {'Box Hill South': 4372.310344827586,
  'Box Hill': 18681.689655172413},
 207031164: {'Box Hill North': 14187.906976744185,
  'Mont Albert North': 4877.093023255814},
 207031165: {'Burwood': 14551},
 207031166: {'Burwood East': 10972},
 207031167: {'Mont Albert': 6457.181818181818,
  'Surrey Hills': 3689.818181818182},
 208011168: {'Beaumaris': 14844},
 208011169: {'Brighton': 24172},
 208011170: {'Brighton East': 15996.153846153846,
  'Brighton': 639.8461538461539},
 208011171: {'Cheltenham': 4338.692307692308,
  'Highett': 7713.2307692307695,
  'Sandringham': 482.0769230769231},
 208011172: {'Hampton East': 4786.25,
  'Hampton': 13401.5,
  'Brighton East': 478.625,
  'Brighton': 478.625},
 208011173: {'Black Rock': 7064.129032258064,
  'Sandringham': 11184.870967741936},
 208021174: {'Bentleigh': 16678.666666666664, 'McKinnon': 8339.333333333332},
 208021176: {'Carnegie': 19484.276315789473, 'Murrumbeena': 800.7236842105262},
 208021177: {'St Kilda East': 3302.0884955752213,
  'Caulfield East': 2063.8053097345132,
  'Caulfield North': 17955.106194690266},
 208021178: {'Caulfield': 8572.107142857143,
  'Caulfield South': 9890.892857142857},
 208021179: {'Gardenvale': 1487.3999999999999, 'Elsternwick': 10907.6},
 208021180: {'Hughesdale': 8313},
 208021181: {'Murrumbeena': 9859},
 208021182: {'Glen Huntly': 5883.3432835820895, 'Ormond': 8194.65671641791},
 208021426: {'McKinnon': 735.2608695652174,
  'Ormond': 367.6304347826087,
  'Bentleigh East': 15808.108695652174},
 208021427: {'Bentleigh': 448.2727272727273,
  'Bentleigh East': 14344.727272727274},
 208031183: {'Aspendale Gardens': 9226},
 208031184: {},
 208031185: {'Carrum': 7841.476190476191,
  'Patterson Lakes': 4825.523809523809},
 208031186: {'Chelsea': 7101.45, 'Bonbeach': 8679.550000000001},
 208031187: {},
 208031188: {'Cheltenham': 20784.145161290322, 'Highett': 4482.854838709678},
 208031189: {'Edithvale': 5677.6, 'Aspendale': 8516.4},
 208031190: {'Mentone': 13801},
 208031191: {'Heatherton': 1693.5652173913043, 'Moorabbin': 8044.434782608696},
 208031192: {},
 208031193: {'Parkdale': 9971.833333333334, 'Mordialloc': 12071.166666666668},
 208041194: {'Malvern East': 264.1125,
  'Malvern': 6866.925,
  'Glen Iris': 13469.7375,
  'Kooyong': 528.225},
 208041195: {'Malvern East': 23475},
 209011196: {'Bundoora': 10329},
 209011197: {'St Helena': 730.6896551724138,
  'Eltham North': 730.6896551724138,
  'Greensborough': 19728.62068965517},
 209011198: {'Rosanna': 6526.557692307692, 'Heidelberg': 9634.442307692307},
 209011199: {'Ivanhoe': 2056.2666666666664,
  'Heidelberg Heights': 7453.966666666667,
  'Bellfield': 1799.2333333333333,
  'Heidelberg West': 4112.533333333333},
 209011200: {'Ivanhoe': 12687},
 209011201: {'Eaglemont': 3745.8461538461543,
  'Ivanhoe East': 4370.153846153846},
 209011202: {'Montmorency': 9003.70588235294,
  'Lower Plenty': 5002.058823529412,
  'Briar Hill': 3001.2352941176473},
 209011203: {'Viewbank': 6673.411764705883,
  'Yallambie': 1112.235294117647,
  'Macleod': 11122.35294117647},
 209011204: {'Watsonia North': 2141.333333333333,
  'Watsonia': 7494.666666666667},
 209021205: {'Bundoora': 4117.721518987342,
  'Kingsbury': 3129.46835443038,
  'Macleod': 5764.810126582278},
 209021207: {'Preston': 264.1607142857143, 'Reservoir': 29321.839285714286},
 209021208: {'Preston': 350.05479452054794, 'Reservoir': 25203.94520547945},
 209021428: {'Preston': 23205},
 209021429: {'Preston': 12506.928571428572, 'Coburg North': 962.0714285714286},
 209031209: {'Eltham': 17967.0, 'Eltham North': 5989.0},
 209031210: {'Hurstbridge': 3584},
 209031211: {},
 209031212: {'Panton Hill': 5412},
 209031213: {'Plenty': 2445.5, 'Greensborough': 7336.5},
 209031214: {'North Warrandyte': 7141},
 209031215: {'Diamond Creek': 14715},
 209041216: {'Bundoora': 8668},
 209041217: {'Bundoora': 6639},
 209041219: {'Lalor': 24689},
 209041220: {'Mill Park': 18066},
 209041221: {'Mill Park': 11959},
 209041223: {'Bundoora': 398.2307692307692, 'Thomastown': 20309.76923076923},
 209041224: {'Upper Plenty': 530.2142857142857,
  'Bylands': 530.2142857142857,
  'Wallan': 14846.0,
  'Wandong': 530.2142857142857,
  'Beveridge': 5832.357142857143},
 209041225: {'Whittlesea': 550.2222222222222,
  'Yan Yean': 550.2222222222222,
  'Donnybrook': 8803.555555555555},
 209041430: {'Doreen': 28685},
 209041431: {'Epping': 13501},
 209041432: {'Epping': 8296},
 209041433: {'Epping': 13150},
 209041434: {'Mernda': 25051},
 209041435: {'South Morang': 11774.0, 'Wollert': 1682.0},
 209041436: {'South Morang': 12375},
 209041437: {'Wollert': 22785},
 210011226: {'Airport West': 8540},
 210011227: {},
 210011228: {'Keilor': 5101.714285714285, 'Keilor Park': 3826.285714285714},
 210011229: {'Avondale Heights': 16725.96226415094,
  'Keilor East': 11870.037735849057},
 210011230: {'Niddrie': 5922.68, 'Essendon West': 1870.32},
 210011231: {'Strathmore': 9564.32, 'Strathmore Heights': 831.6800000000001},
 210021232: {'Gisborne': 12223.157894736842,
  'New Gisborne': 2291.842105263158},
 210021233: {'Mount Macedon': 3697},
 210021234: {'Riddells Creek': 4469},
 210021235: {'Romsey': 4286.0, 'Lancefield': 4286.0, 'Monegeetta': 2143.0},
 210031236: {'Pascoe Vale': 444.25, 'Coburg North': 8440.75},
 210031237: {'Fawkner': 14906},
 210031239: {'Pascoe Vale South': 324.90361445783134,
  'Oak Park': 7472.78313253012,
  'Pascoe Vale': 18844.409638554218,
  'Hadfield': 324.90361445783134},
 210031438: {'Hadfield': 253.5979381443299, 'Glenroy': 24345.40206185567},
 210031439: {'Gowanbrae': 2098.6666666666665,
  'Tullamarine': 1049.3333333333333},
 210031440: {'Hadfield': 6131},
 210041240: {'Sunbury': 13683},
 210041241: {'Diggers Rest': 6632.7058823529405,
  'Sunbury': 25583.294117647056},
 210051242: {'Jacana': 2191.6363636363635, 'Broadmeadows': 11584.363636363636},
 210051243: {'Coolaroo': 744.6363636363636,
  'Dallas': 9680.272727272728,
  'Fawkner': 1489.2727272727273,
  'Campbellfield': 4467.818181818181},
 210051245: {'Westmeadows': 9643.857142857143,
  'Attwood': 1753.4285714285713,
  'Gladstone Park': 7013.714285714285},
 210051246: {'Bulla': 1305.764705882353,
  'Greenvale': 19586.470588235294,
  'Oaklands Junction': 1305.764705882353},
 210051247: {'Meadow Heights': 14943},
 210051248: {},
 210051249: {'Roxburgh Park': 24801},
 210051250: {'Tullamarine': 6657},
 210051441: {'Craigieburn': 8207},
 210051442: {'Craigieburn': 13028},
 210051443: {'Craigieburn': 21980},
 210051444: {'Craigieburn': 22931},
 210051445: {'Mickleham': 10194.107142857143, 'Kalkallo': 8834.892857142857},
 211011251: {'Boronia': 995.3846153846155, 'Bayswater': 11944.615384615385},
 211011254: {'Wantirna South': 4052.235294117647,
  'Scoresby': 8104.470588235294,
  'Knoxfield': 5065.294117647059},
 211011255: {'Lysterfield': 6893},
 211011256: {'Rowville': 15698},
 211011257: {'Rowville': 8276},
 211011258: {'Rowville': 10586},
 211011259: {'Wantirna': 14248},
 211011260: {'Wantirna South': 18746},
 211011446: {'Boronia': 23935},
 211011447: {'Ferntree Gully': 14487},
 211011448: {'Upper Ferntree Gully': 3398.8888888888887,
  'Ferntree Gully': 11896.111111111111},
 211011449: {'The Basin': 4415},
 211021261: {'Park Orchards': 1038.5, 'Donvale': 15577.5},
 211021262: {'Wonga Park': 2073.8, 'Warrandyte': 6221.4, 'Donvale': 2073.8},
 211031263: {'Bayswater North': 9148.5, 'Kilsyth South': 3049.5},
 211031265: {'Croydon Hills': 3078.333333333333,
  'Croydon North': 15391.666666666668},
 211031266: {'Croydon': 411.5652173913043, 'Ringwood': 18520.434782608696},
 211031267: {'Heathmont': 4307.400000000001,
  'Ringwood': 861.48,
  'Ringwood East': 16368.12},
 211031268: {'Ringwood North': 9794},

In [50]:
result1

{'Surrey Hills': 48984,
 'Ferntree Gully': 29782,
 'St Kilda East': 41212,
 'Deanside': 42411,
 'Highett': 37801,
 'Burwood': 34953,
 'Point Cook': 80064,
 'Murrumbeena': 30144,
 'Wantirna South': 35968,
 'Hoppers Crossing': 39177,
 'Werribee': 56286,
 'Wollert': 36241,
 'Rowville': 34560,
 'Preston': 91814,
 'Sunbury': 45899,
 'Macleod': 31920,
 'Cranbourne South': 37599,
 'Narre Warren South': 60800,
 'Reservoir': 55140,
 'Williamstown': 36677,
 'McKinnon': 41929,
 'Greensborough': 30972,
 'Noble Park': 32491,
 'Port Melbourne': 18432,
 'Clyde': 76241,
 'Elwood': 45234,
 'Donvale': 26985,
 'Fitzroy North': 27999,
 'Brunswick West': 44931,
 'Templestowe Lower': 26053,
 'Narre Warren': 28743,
 'Caroline Springs': 42527,
 'Oakleigh South': 35995,
 'Frankston': 43492,
 'Endeavour Hills': 25596,
 'Mill Park': 30025,
 'Bentleigh East': 31704,
 'Shepparton': 44215,
 'Warrnambool': 35957,
 'Bentleigh': 39811,
 'Windsor': 50639,
 'Cheltenham': 37801,
 'Armstrong Creek': 64368,
 'Armadale': 31604,
 'Ringwood East': 26483,
 'Hillside': 39255,
 'Croydon': 50189,
 'Southbank': 39616,
 'Fairfield': 20283,
 'Doncaster': 51573,
 'Brighton': 59953,
 'Brighton East': 35781,
 'Officer': 46678,
 'Alphington': 20283,
 'Mont Albert': 26466,
 'Malvern East': 44604,
 'Doncaster East': 31161,
 'Hawthorn': 41782,
 'Melbourne': 210570,
 'Beaconsfield': 52687,
 'South Morang': 25831,
 'Hadfield': 57697,
 'Coburg North': 22354,
 'St Albans': 38490,
 'Pakenham': 57726,
 'Boronia': 36875,
 'St Kilda': 47139,
 'Sandringham': 30783,
 'Pascoe Vale South': 66818,
 'Brunswick East': 43829,
 'Glen Iris': 38489,
 'Thornbury': 47683,
 'Kilsyth': 26668,
 'Ringwood': 40469,
 'Craigieburn': 66146,
 'Ormond': 30989,
 'Berwick': 53459,
 'Glen Waverley': 41928,
 'Tullamarine': 9805,
 'Fawkner': 31288,
 'Williams Landing': 49370,
 'Mildura': 33297,
 'Pascoe Vale': 35852,
 'Ivanhoe': 28109,
 'Mount Waverley': 36010,
 'Bundoora': 59356,
 'Epping': 34947,
 'Camberwell': 72921,
 'South Yarra': 30642,
 'Flemington': 10777,
 'Truganina': 52835,
 'Eltham North': 45146,
 'Coburg': 39851}

In [51]:
pd.DataFrame(result)

,201011001,201011002,201011003,201011004,201011005,201011006,201011007,201011008,201021009,201021010,...,217031471,217031472,217031473,217031474,217031475,217031476,217041477,217041478,217041479,217041480
Lucas,5004.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cardigan,417.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alfredton,10842.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lake Wendouree,NaN,2609.90625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bakery Hill,NaN,745.68750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Hawkesdale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2494.25,NaN,NaN
Mailors Flat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2494.25,NaN,NaN
Port Fairy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4988.50,NaN,NaN
Warrnambool,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22586.0,12584.470588
Allansford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,786.529412

In [52]:
df = pd.DataFrame(result)
r2 = df.sum(axis=1)
r = pd.DataFrame(r2)
r.to_csv("../data/raw/result1.csv")

In [53]:
r1 = pd.DataFrame.from_dict(result1,orient='index')
r1.to_csv("../data/raw/Multiple_SA2_correspond_to_one_locality.csv")

In [54]:
r1

                    0
Surrey Hills    48984
Ferntree Gully  29782
St Kilda East   41212
Deanside        42411
Highett         37801
...               ...
South Yarra     30642
Flemington      10777
Truganina       52835
Eltham North    45146
Coburg          39851

[93 rows x 1 columns]